name: 'manual'
on: 
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: Hello
                required: true
                description: A cheerful word
            choise:
                type: choice
                options:
                    - info
                    - warn
                    - error


jobs:
    manual:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{inputs.greeting}}"
        