name: concurrency
on:
    push:
        paths: [".github/**/*.ya?ml"]

defaults:
    run:
        shell: bash
concurrency: 
    group: ${{github.workflow}}
    cancel-in-progress: true

jobs:
    concurrency:
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
            - run: sleep 130
